ARG HDF5_VERSION
FROM hhoeflin/hdf5r_devel:$HDF5_VERSION

# copy the local context
USER docker
COPY --chown=docker:docker . /home/docker/hdf5r

ENTRYPOINT [ /bin/bash ]

RUN cd /home/docker/hdf5r \
    && R CMD build . \
    && R CMD check hdf5r_*.tar.gz
