ARG DEB_HDF5_IMG

FROM $DEB_HDF5_IMG

# copy the local context
USER docker
COPY --chown=docker:docker . /home/docker/hdf5r

ENTRYPOINT [ /bin/bash ]

ARG BUILD_OUTPUT
ARG CRAN_CHECK_ARG
RUN cd /home/docker/hdf5r \
    && export _R_CHECK_CRAN_INCOMING="false" \
    && R CMD check ${CRAN_CHECK_ARG} ${BUILD_OUTPUT} || true

