.PHONY: clean all copy
clean all copy:
	$(MAKE) -C CWrappers_1.12.0 $@
	$(MAKE) -C CWrappers_1.10.3 $@
	$(MAKE) -C CWrappers_1.10.2 $@
	$(MAKE) -C CWrappers_1.10.0 $@
	$(MAKE) -C CWrappers_1.8.16 $@
	$(MAKE) -C CWrappers_1.8.14 $@
	$(MAKE) -C CWrappers_1.8.12 $@
